@url = https://api.multiversx.com
@userAddress = erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th
@contractAddress = erd1qqqqqqqqqqqqqpgqvc7gdl0p4s97guh498wgz75k8sav6sjfjlwqh679jy
@transaction = 684d46173811638e0cb11a44d5dda68ae1c5b6dd103069a8a650bec0f416ca5f

### Get network config

GET {{ url }}/network/config HTTP/1.1
Content-Type: application/json

### Get account (user)

GET {{ url }}/accounts/{{ userAddress }} HTTP/1.1
Content-Type: application/json

### Get account (contract)

GET {{ url }}/accounts/{{ contractAddress }} HTTP/1.1
Content-Type: application/json

### Get transaction

GET {{ url }}/transactions/{{ transaction }} HTTP/1.1
Content-Type: application/json
