@url = https://api.multiversx.com
@userAddress = erd1r44w4rky0l29pynkp4hrmrjdhnmd5knrrmevarp6h2dg9cu74sas597hhl
@contractAddress = erd1qqqqqqqqqqqqqpgqvc7gdl0p4s97guh498wgz75k8sav6sjfjlwqh679jy
@transaction = 684d46173811638e0cb11a44d5dda68ae1c5b6dd103069a8a650bec0f416ca5f
@fungibleToken = WEGLD-bd4d79
@nonFungibleTokenIdentifier = VOTEPROOF-19034b
@nonFungibleTokenNonce = 01

### Get network config

GET {{ url }}/network/config HTTP/1.1
Content-Type: application/json

### Get account (user)

GET {{ url }}/accounts/{{ userAddress }} HTTP/1.1
Content-Type: application/json

### Get account (contract)

GET {{ url }}/accounts/{{ contractAddress }} HTTP/1.1
Content-Type: application/json

### Get transaction

GET {{ url }}/transactions/{{ transaction }} HTTP/1.1
Content-Type: application/json

### Get account tokens (fungible)

GET {{ url }}/accounts/{{ userAddress }}/tokens HTTP/1.1

### Get account tokens (non-fungible)

GET {{ url }}/accounts/{{ userAddress }}/nfts HTTP/1.1

### Get account token (fungible)

GET {{ url }}/accounts/{{ userAddress }}/tokens/{{ fungibleToken }} HTTP/1.1

### Get account token (non-fungible)

GET {{ url }}/accounts/{{ userAddress }}/nfts/{{ nonFungibleTokenIdentifier }}-{{ nonFungibleTokenNonce }} HTTP/1.1
